---
production:
  hosts:
    bd-web:
      ansible_host: "{{ lookup('env', 'BD_WEB_HOST') }}"
      ansible_user: root  # Will be 'deploy' after initial setup
      ansible_port: 22
      ansible_python_interpreter: /usr/bin/python3
